### ISSUE TITLE
beforeGroup should be triggered by the group rather than the test

### ISSUE THREAD

**Issue by nickgieschen** [JetBrains/spek#159]
I have an integration test where I need to start a web server prior to the tests. I have 

```
context("routes"){

beforeGroup(){
   startServer()
}

context("request blah blah"){
   val response = sendRequest()
   it("should blah blah"){
    assertThat(blah);
  }
}
}
```
However, it looks like beforeGroup only gets called once "it" is run and thus the webserver is obviously not started at the time sendRequest is called. The docs say "Spek allows running arbitrary code before and after a group and test is executed", but this is not true, as far as I can tell. The beforeGroup code only gets executed once the "it" within the group is called.

**Comment by raniejade** [comment]
This is working as expected. Spek has two phases, discovery and execution. `group` scopes are evaluated eagerly during the discovery phase, this due to how Spek is structured. While `tests` and `action` scopes are evaluated on the execution phase. So in your example, `val response = sendRequest()` is evaluated during the discovery phase.  To fix your problem use `on` (which creates an `action` scope):

```kotlin
context("routes") {
    beforeGroup() {
        startServer()
    }

    on("request blah blah") {
       val response = sendRequest()

       it("should blah blah") { ... }
    }
}
```
