### ISSUE TITLE
Replace DSL Extensions with Public Methods

### ISSUE THREAD

**Issue by arturdryomov** [JetBrains/spek#284]
It is kind of annoying to import DSL operators semi-manually. Yes, the IDE most of the time will suggest the right thing, but it is still confusing to see DSL operators as “optional” extensions. Technically it is nice to see how it is done via extensions, the real world usability is not so great. If we all agree about DSL stability across releases this shouldn’t be an issue.

Pros.
* Less semi-manual imports which take seconds every time you write new test and is very annoying.
* Better adoption rate because of less confusion “what to import”.

Cons.
* None?

**Comment by raniejade** [comment]
I don't think writing a star import (`import org.spekframework.spek2.dsl.standard.*`) is that hard. Using extension methods allows developers to import only what they need - if they have their own synonyms they don't need to import the ones we provide (`import org.company.our_style.*`). Spek for me is prescriptive yet flexible.

**Comment by arturdryomov** [comment]
We are creating a lot of tests in a single day, manual import is tedious because it is manual.

Actually I think it is a good mnemonic.
* No need to import — you are using standard DSL.
* Need to import — OK, this is custom.

**Comment by raniejade** [comment]
> Actually I think it is a good mnemonic.
> 
> No need to import — you are using standard DSL.
> Need to import — OK, this is custom.

But that would pollute the completion provided by the IDE.

**Comment by artem-zinnatullin** [comment]
Problem with `import org.spekframework.spek2.dsl.standard.*` is that it's not what IntelliJ does by default, default code style only starts `*` after 5 imports from same namespace, so it's a pretty manual job for most of the users…

Problem with putting standard DSL directly into `Spek` is that user potentially won't be able to have custom DSL with same function names, but I think this is good since we won't have questions from users like "My `context/describe/on` works not as expected only to figure out that it's not DSL provided by Spek

**Comment by raniejade** [comment]
I still don't see any issue on doing imports for using synonyms, any good IDE can do it for you. Confusion on what to import can be easily addressed in the docs.

I don't want Spek to be too prescriptive, yes we provide a set of standard synonyms but we don't force users to use them.

**Comment by artem-zinnatullin** [comment]
@raniejade that just seems like friction point that we could remove by default and not force boilerplate

```
"wait for ide to analyze file" → "wait for import autocomple" → "import"
``` 

cycle to be applied by every user for every new part of DSL used in a spec. This is especially painful when you edit huge existing spec and want to use DSL part that wasn't used in it before (IDE lags a lot)

Less friction points — happier users :) 

It's very similar to idea of Spek Gradle plugins provided by us, instead of manual configuration.

>I don't want Spek to be too prescriptive, yes we provide a set of standard synonyms but we don't force users to use them.

That's a valid point, but don't we expect "99%" of users to just use standard DSL anyways? We also don't block them from creation custom DSL with different function names…

**Comment by raniejade** [comment]
Ok fine :), but I'm still not convinced that the manual import is the issue.

> Problem with putting standard DSL directly into Spek is that user potentially won't be able to have custom DSL with same function names, but I think this is good since we won't have questions from users like "My context/describe/on works not as expected only to figure out that it's not DSL provided by Spek.

This makes sense :+1:

**Comment by raniejade** [comment]
#306 has been merged, closing this issue.
