### ISSUE TITLE
Provide Focus and Exclusion Operators

### ISSUE THREAD

**Issue by arturdryomov** [JetBrains/spek#285]
* Focus — prefix group and test operators with `f`.
* Exclusion — prefix group and test operators with `x`.

This can be achieved via IJ plugin, but it should be noted that not everybody uses IJ and will use JUnit 5 for a considerable amount of time, since it will require migration.

From my personal standpoint, plugin should be a bonus to Spek experience and not its corner stone. Sometimes I can use Vim to edit a test quickly and run it from console — especially in GUI-less environments (yeah, that’s horrible).

Pros.
* Focus or exclude without IJ plugin or JUnit 5 runner.
* Parity with other BDD libraries, such as Quick for Swift.

Cons.
* None?
* One left `f()` in Spek can be merged accidentally because it’s a very tiny code change and cause false-positive test results.

**Comment by artem-zinnatullin** [comment]
I also give my vote for this feature, it's useful, especially in case when Spek IntelliJ plugin has compatibility issues with new releases of IntelliJ/Android Studio.

@raniejade can we reuse `Path` abstraction to run part of the test tree `f` or we'll need to add separate support apis for `f`? I imagine `x` will require separate support anyways to report test as disabled.

**Comment by raniejade** [comment]
We could add a filter step after the discovery phase to support `f` as an extension. Early Spek versions `f` was implemented in two phases, (1) search for focused scope (2) traverse tree to remove non-focused branches.

**Comment by artem-zinnatullin** [comment]
Yeeep, SGTM! 

I'd actually like to work on it if you don't mind, to dive deeper into test runner mechanism, you changed it pretty significantly since I touched it last time :)

Also, as a side-effect of this issue implementation we could try to extract Introspection API that'll sit expose parts of Discovery, Filtering and Running phases and allow user develop extensions (ie Robolectric integration), but I think this is more 3.x stuff (or never because I like that Spek is just a program flow unlike JUnit when it's a mix of imperative code execution with annotation and reflection based hooks into certain parts)

This issue is also somewhat related to #219.

**Comment by raniejade** [comment]
Sure, go ahead! :)

**Comment by arturdryomov** [comment]
BTW it can be helpful to add some warnings to the output about `f` and `x` usage as a tip to remove them afterwards (in case someone added them for debugging purposes).
