### ISSUE TITLE
Invalid dependency declaration in pom

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#317]
I missed this out previously, looking a way to fix it without changing the project's `group`. 

```
    <dependency>
      <groupId>spek.spek-dsl</groupId>
      <artifactId>common</artifactId>
      <version>1.1.5</version>
      <scope>compile</scope>
    </dependency>
```

**Comment by raniejade** [comment]
I got two options: a hacky and non-hacky one. For the non-hacky just change to a flat structure and everything will work, while the hacky one requires some fiddling with gradle. cc @artem-zinnatullin @ming13 @hhariri

**Comment by jaredsburrows** [comment]
What is the problem here? What the desired G:A:V? Ideally you want your module name to match the `artifactId`. The group name and version number should be the same for all artifacts.

**Comment by artem-zinnatullin** [comment]
@jaredsburrows you can find details of the problem in PR #342

TL;TR: because of how we organised modules in the project (hierarchical folders) Gradle screwed up `groupId` and `artifactId` of our cross-module dependencies

**Comment by jaredsburrows** [comment]
@artem-zinnatullin I would vote to rewrite how you publish it using `gradle.properties` and remove extra folders. This will help simply things in your pull request. You should not have to rewrite the `POM` unless you want something custom(eg. https://github.com/jaredsburrows/gradle-spoon-plugin/blob/master/gradle/publish.gradle#L84).

See @JakeWharton's Butterknife repo here: https://github.com/JakeWharton/butterknife.

Have a single `gradle.properties` for the `POM` in the root: https://github.com/JakeWharton/butterknife/blob/master/gradle.properties.

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.jakewharton</groupId>
  <artifactId>butterknife</artifactId>
  <version>8.8.1</version>
  <packaging>aar</packaging>
  <name>Butterknife</name>
</project>
```

Then for individual modules where you want to override the `groupId` and/or `artifactId`, you can put another `gradle.properties` in the individual module/artifact: https://github.com/JakeWharton/butterknife/blob/master/butterknife-compiler/gradle.properties.

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.jakewharton</groupId>
  <artifactId>butterknife-compiler</artifactId>
  <version>8.8.1</version>
  <name>Butterknife Compiler</name>
</project>
```

**Comment by artem-zinnatullin** [comment]
@jaredsburrows `gradle.properties` wouldn't solve this particular issue. Each module's groupId/artifactId were already set correctly in the pom, but cross-module dependencies were declared incorrectly. 

I've used the structure you're talking about for a long time and never really liked it because you still need some code in `.gradle` files as well as `.properties`, which only complicates stuff. In Spek we keep all publishing related info in single `.gradle` file which for me sounds more maintainable. (I need to clearup root `build.gradle` to remove remaining bits)

>and remove extra folders

We've specifically decided to make project structure hierarchical when it became a multi-platform project and amount of modules started to grow. This way it's more organized. I better fix Gradle one-way or another to achieve that. If that argument doesn't look valid I have another example — at work we have project with 300+ Gradle modules, you can imagine that flat structure would not be maintainable 😸 (I'm not advocating for such large projects, just in case)

If you still think it's not a valid response — I encourage you to try fix it another way and submit a PR :)

**Comment by jaredsburrows** [comment]
@artem-zinnatullin Sure, there are many solutions for this. Since you merged your other PR and closed this one it should be ok.
