### ISSUE TITLE
Release date of 2.0 ?

### ISSUE THREAD

**Issue by Petikoch** [JetBrains/spek#352]
Hello @artem-zinnatullin ,

you said in November 2017 at the KotlinConf (https://www.youtube.com/watch?v=R425cc6XrvA) that 

- developers who are not already using Spek should wait for Spek 2.x
- a release will be around at the end of November 2017

We are very much looking forward to 2.0! 

When do you think 2.0 will be available? It's January 2018 now ;-)

Best regards,
Peti

**Comment by artem-zinnatullin** [comment]
Hi Peti, this is solely my fault :(

Right after KotlinConf I had and still have very pressuring work, in
December I had to take a long vacation due to personal problems.

I'm coming back from vacation on Friday and finishing my part of Spek tasks
for 2.0 is top priority after work.

I'm very sorry for inconvenience..

**Comment by Petikoch** [comment]
Thank you @artem-zinnatullin for the answer and all the best for you!

**Comment by raniejade** [comment]
@artem-zinnatullin Don't take all the blame man, I'm partly responsible for it as well - been busy with the new job.

**Comment by kevinjom** [comment]
any news of 2.0 release?

**Comment by Petikoch** [comment]
2.0.0 was released, congrats!

https://github.com/spekframework/spek/releases/tag/2.0.0
