### ISSUE TITLE
Context not being resetted between 'on' cases

### ISSUE THREAD

**Issue by LeoColman** [JetBrains/spek#434]
I expected a new Foo to be created for every 'on' scenario, but instead it reuses the object, therefore I can't use the same logic for all the tests that modify the object.

What can I do to achieve this?

```
class Foo(var bar: String = "bar")

object SpekTest : Spek({
    
    given("A Foo foo") {
        val foo = Foo()
        
        on("Change to foo") {
            foo.bar = "foo"
            
            it("Should have changed") {
                assertEquals("foo", foo.bar)
            }
        }
        
        on("No change") {
            it("Should not have changed") {
                assertEquals("bar", foo.bar)
            }
        }
        
    }
    
})
```

**Comment by NorseDreki** [comment]
>new Foo to be created for every 'on' scenario

Use `val foo by memoized { Foo() }` instead of `val foo = Foo()` as the latter is evaluated only once.

---
BTW,  there seems to be an inconsistent behavior:

`memoized` uses `CachingMode.TEST` by default which means value should be re-created for every `it` (test scope), _but_ it is re-created for every `on` here (action scope), for example:

```
...
val foo by memoized { Foo() }

on("Change to foo") {
    foo.bar = "foo"

    it("Should have changed") {
        assertEquals("foo", foo.bar)
    }

    it("Should not have changed as well") {
        assertEquals("bar", foo.bar)
    }
}
```

"Should not have changed as well" test fails as both `it`s get the same instance of `foo`.

Looks like a bug to me.

**Comment by raniejade** [comment]
@upelsin that's expected since action is treated as a `test` by memoized.

**Comment by NorseDreki** [comment]
@raniejade probably `CachingMode.ACTION` could have been a less confusing name then.
