### ISSUE TITLE
stderr output is shown in the wrong test

### ISSUE THREAD

**Issue by peterholak** [JetBrains/spek#560]
If a test manually outputs something to `System.err`, it's sometimes visible next to the wrong test in the test runner. Sometimes lines are missing, or outputs from different tests are grouped together, or only visible in the group, etc.

This doesn't happen with `System.out` - everything works fine there.

Android Studio 3.2.1, Spek 2.0.0-rc.1, AS plugin 2.0.0-rc.1.169+2c45d6a-Studio3.2, android-junit5 1.3.2.0

```kotlin
object StderrExample : Spek({
    (1..5).forEach { group ->
        describe("group $group") {
            (1..5).forEach { test ->
                it("test $test in group $group") {
                    System.err.println("$group: $test")
                }
            }
        }
    }
})
```

**Comment by raniejade** [comment]
@peterholak ~is still happening in `2.0.0`?~ Actually it is still happening. It's probably broken because of this: https://github.com/spekframework/spek/blob/2.x/spek-ide-plugin/interop-jvm/src/main/kotlin/org/spekframework/ide/ServiceMessageAdapter.kt#L91 and I'm not inclined to fix it. It's either this or broken test tree reporting in the IDE.
