### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by dhaksddj** [JetBrains/spek#570]
Does this project has significant support behind it? I see multiple issues that look really bad, PRs not merged for months and very poor documentation for a beginner.

**Comment by vanniktech** [comment]
Do you want to help out?

**Comment by dhaksddj** [comment]
Sorry for my terseness. We are evaluating tools for a new project and work and I've been assigned the due diligence. Can you give some information on the state of play of this project right now? Is it struggling with lack of resources? Are you actively looking for devs to help out? How does the future look?

**Comment by jcornaz** [comment]
Since I'm not the maintainer, my comment here is only personal opinion.

1. Open PR request is not a good measurement IMHO. Any well maintained project can have PR staying open forever and even for good reasons. You'd better look at the *close* PR. And you'll see a bunch of recently merged PR: https://github.com/spekframework/spek/pulls?q=is%3Apr+is%3Aclosed.
2. Commits to the main branch in during the past year, shows that work is done on this project: https://github.com/spekframework/spek/graphs/contributors?from=2018-01-21&to=2019-01-21&type=c
3. @raniejade Answered quite fast to most of the recent issues.
4. A new version of the IntelliJ plugin has been published last week.

So for me, activity seems fine. At least for a small open source project.

>I see multiple issues that look really bad

There is indeed few critical issues to be solved. In my opinion #566 is really problematic and dangerous.  But the most critical issues are also the ones reported the most recently. And that's normal, isn't it? Time and effort is needed to solve theses issues.

>very poor documentation for a beginner

I agree the doc is not fantastic. But in the other hand there is not a lot to say either. If you read and understand the [core concepts](https://spekframework.org/core-concepts/), then you are already good to go. Remember it is "only" a test framework. Assertion, mocks, writing good tests etc. are not part of Spek. 

About the documentation, I'd like to say "try", and you'll see if you encounter problems due to the lack of documentation or not. And if you do, please open an issue saying what should be changed or added in the documentation. Personally I learned very quickly and did not encounter major issue due to the lack of documentation. It felt the opposite of RxJava which has a very great documentation, but which is very hard to learn.

**Comment by dhaksddj** [comment]
Thank you for your response.

**Comment by raniejade** [comment]
@jcornaz is spot on, I wont pry any longer. The issues do need some house keeping, most of them are several years old and may not apply anymore.
