### ISSUE TITLE
Fixtures run in different thread

### ISSUE THREAD

**Issue by nlwillia** [JetBrains/spek#725]
I have a test that's breaking when migrated to Spek2 because it configures a ThreadLocal in `beforeGroup` which runs in the discovery phase in the main thread, but the test itself now runs in a separate worker thread that can't see that information.

It looks like I can work around this using `beforeEachTest`, though that means the setup code runs per test instead of per group.

I imagine that it's impractical to provide an option that would guarantee the group fixture runs on the same thread as the test, but I thought I'd check, and mention the migration gotcha.

**Comment by raniejade** [comment]
> It looks like I can work around this using beforeEachTest, though that means the setup code runs per test instead of per group.

Actually, it's the recommend way to setup test dependencies. As an alternative you can use `memoized`.

```kotlin
val foo by memoized { ThreadLocalFoo() }
```

If you're using the specification style (describe, it) then you have guarantees that foo is initialized on the same thread as the test (including fixtures) since the default `CachingMode` is set to `TEST` (each test will receive a new value).

No guarantees on the gherkin since the default `CachingMode` is `SCOPE` for `Scenario`s and `EACH_GROUP` for `Feature`s. It also kinda make sense to have all test under `Scenario` to run on the same thread (will probably make this change in the future).

Closing this as _answered_, but feel free to re-open if I miss something.

**Comment by nlwillia** [comment]
That helps, thanks.
