### ISSUE TITLE
IntelliJ test runner doesn't stop after all tests have executed

### ISSUE THREAD

**Issue by cristianrgreco** [JetBrains/spek#848]
Our project uses Kotlin and Micronaut. We extend Spek to start and stop a server as shown:

```kotlin
object SpekConfiguration {
    fun Root.startApp() {
        val embeddedServer = ApplicationContext.run(EmbeddedServer::class.java)

        afterGroup {
            embeddedServer.stop()
        }
    }
}

---

object Test : Spek({
    startApp()

    group("Group") {
        test("Test") {
            ...
        }
    }
})
```

This works as expected. The tests all run with IntelliJ but the runner does not stop when they finish. 

If I do not start the server then the tests correctly stop. Debugging the `afterGroup` shows that the server is being stopped. My guess would be that when the tests complete, the Spek runner tries to terminate before the afterGroup is called which leaves the test runner running.

**Comment by raniejade** [comment]
I'm pretty sure there was a related ticket about this, I can't find it anymore. The problem here is that the Micronaut embedded server is leaving some non-daemon thread running which stops the jvm from shutting down. JUnit does an explicit System.exit(0) to workaround this, but spek does not. Looks like this is a pretty common problem, so I'm happy to include the hack in spek as well.

**Comment by cristianrgreco** [comment]
Thanks @raniejade !
