### ISSUE TITLE
Upgrade to JUnit 5

### ISSUE THREAD

**Issue by raniejade** [JetBrains/spek#86]
A custom JUnit 5 engine needs to be implemented, we should preserve the current behavior as much as possible.

**Comment by mfulton26** [comment]
I checked out the junit5 branch and I'm liking very much what I see. One behavior though that I believe is worthwhile to change is that instead of resolving the specs up front before execution that specs start running before resolving groups/tests and dynamically registers/adds them to the JUnit5 TestPlan, etc. This way work can be done outside of test blocks and not delay user feedback, etc. Thoughts?

**Comment by raniejade** [comment]
I see no value in delaying the discovery of groups/tests, ideally there should not be any logic in group blocks aside from setting up the spec. Initialisation and cleaning up can be done in the fixtures (`beforeEach` and `afterEach`, respectively - we could also add `before` and `after` later on).

**Comment by mfulton26** [comment]
When unit testing I completely agree but when your setup involves creating `RemoteWebDriver` instances for testing UI web components across various web browsers/platforms using Sauce Labs or a similar Selenium Grid then your setup time becomes a nuisance as instantiating your tests takes longer than running them.

With that said, I haven't tried using the `beforeEach` yet. It would force me to use `var` instead of `val` in some cases and potentially `WebDriver?` instead of `WebDriver`. I'll take a look and see if I can't provide a meaningful example that demonstrates the issue well.

**Comment by raniejade** [comment]
Ahhh saucelabs again :). This use case most likely fall on how to extend Spek, which is in the roadmap.

You can use subjects, but it feels hacky. By the time Kotlin `1.1` is released, we can do something like this:

```kotlin
class SomeSpec: Spek({
    val driver by let { ... }
})
```

`driver` will only be created the first time is accessed.

**Comment by mfulton26** [comment]
Ah, nice. And yes, Sauce Labs again. :-)

How will `let` differ from `lazy`? Same type of delegation?

**Comment by raniejade** [comment]
`let` (name may change) will be spek specific and it will be tied execution of the spec. Basically you can configure it so that, each test will have their own instance or not.

**Comment by mfulton26** [comment]
Neat. Thanks.

**Comment by andrei-khveras** [comment]
@raniejade could you give any insight why this PR was closed and what's current status/plans for JUnit 5 support?

**Comment by raniejade** [comment]
@andrei-khveras current version Spek `1.1.0` supports JUnit 5 (`1.0.0-M3`). 

```
// setup the plugin
buildscript {
    dependencies {
        classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.0-M3'
    }
}

apply plugin: 'org.junit.platform.gradle.plugin'

junitPlatform {
    platformVersion '1.0.0-M3'
    filters {
        engines {
            include 'spek'
        }
    }
}

repositories {
    maven { url "http://dl.bintray.com/jetbrains/spek" }
}

// setup dependencies
dependencies {
    testCompile 'org.jetbrains.spek:spek-api:1.1.0'
    testRuntime 'org.jetbrains.spek:spek-junit-platform-engine:1.1.0'
}
```
