### ISSUE TITLE
Using value in `Root.setup()` in a fixture

### ISSUE THREAD

**Issue by FrozenSync** [JetBrains/spek#877]
Let there be a setup and a fixture

```
fun Root.setup() {
    val obj by memoized(
        factory = { createObj() },
        destructor = { it.dispose() }
    )
}

object Test: Spek({
   setup()

   Feature("Foo") {
      val obj: Object by memoized()

      lateinit var bar: Bar
      beforeEachScenario {
         bar = Bar(obj) // 'obj' can not be accessed in this context.
      }
})
```
I understand you need `by memoized { ... }` to access values in `Root.setup()`, but that doesn't seem to be possible inside fixtures. Is this a limitation or should it be approached differently?

**Comment by raniejade** [comment]
This because `obj` is created using `CachingMode.TEST` by default, which is not accessible in `beforeEachScenario` (this equivalent to `beforeEachGroup`). So `obj` is only accessible in `{before|after}EachTest` and in the test scopes (Given, Then, etc...). A fix for you use it to specify the caching mode of `obj`.

```kotlin
val obj by memoized(CachingMode.GROUP, destructor = {it.dispose()}) { createObj() }
```

**Comment by raniejade** [comment]
I'm also sorry for the delayed reply @FrozenSync!

**Comment by FrozenSync** [comment]
No worries. :) Thanks for taking your time to answer! It makes sense now.

**Comment by raniejade** [comment]
Closing as answered :)
