### ISSUE TITLE
Why Spek need complex setup for Android compared to Kotest on Android?

### ISSUE THREAD

**Issue by kawpii** [JetBrains/spek#947]
Spek Android Setup

```
// Required as JUnit 5 doesn't support android modules out of the box.
apply plugin: "de.mannodermaus.android-junit5"

android {
    ...

    testOptions {
        junitPlatform {
            filters {
                engines {
                    include 'spek2'
                }
            }
        }
        unitTests.all {
            testLogging.events = ["passed", "skipped", "failed"]
        }
    }
}

dependencies {

    // spek
    testImplementation "org.spekframework.spek2:spek-dsl-jvm:$spek_version"
    testImplementation "org.spekframework.spek2:spek-runner-junit5:$spek_version"

    // spek requires kotlin-reflect, omit when already in classpath
    testImplementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
}

```

Kotest Android Setup

```
android
{
   ...
   testOptions {
      unitTests.all {
        useJUnitPlatform()
     }
  }
}

dependencies {
   testImplementation 'io.kotest:kotest-runner-junit5:version'
}
```

**Comment by raniejade** [comment]
I suspect that we can make spek use the same setup as kotest. Gradle didn't support JUnit 5 before hence we relied upon `de.mannodermaus.android-junit5` to us that support - we probably can drop that now. So to sum it up, the samples are just not up to date.

**Comment by kawpii** [comment]
okay! side question: why chose spek over kotest?

**Comment by raniejade** [comment]
It's really a matter of preference and your needs.

1. API wise, Spek inherits from RSpec and several JS test frameworks - while kotest (previously known as KotlinTest) inherits from ScalaTest.
2. Kotest provides its own assertion library while Spek does not. We don't provide it because developers normally have their own preference. Plus developing an assertion API requires some effort which warrants a more focused attention: see [strikt](https://strikt.io/) and [atrium](https://github.com/robstoll/atrium).
3. Kotest offer more built-in integration and is more flexible in terms of testing style, if you have those requirements then kotest is the one you should use. Spek is less flexible and provides less feature wise, but it is much more simpler.

**Comment by kawpii** [comment]
Please update the docs to the new version. Thanks I'll close this now.
